### ISSUE TITLE
Can we get the script used to reproject STAGE IV data? Or get the recent years of STAGE IV postprocessed?

### ISSUE THREAD

**Issue by openSourcerer9000** [danielbwright/RainyDay#2]
I'm doing an analysis that  includes the more recent years for STAGE IV (until 1/31/24). I want to be sure that the recent data is processed  in the same way  so as to have continuity,  since the dataset available here only goes until 2021.

Thank you,

**Comment by danielbwright** [comment]
Sure. The code is a bit rough (I think it was the first thing I ever wrote in python, almost 10 years ago) but I suspect you'll have the background to sort it out. The data isn't updated because we're currently refactoring RainyDay so that the input data is CF-compliant, the code is faster and more memory-efficient, etc. We hope to have a public release by this summer but if you really want we can probably get you up on that sooner. The documentation isn't updated for those changes.

[RegridStageIV.py.zip](https://github.com/danielbwright/RainyDay/files/14376640/RegridStageIV.py.zip)

**Comment by openSourcerer9000** [comment]
Thanks for your quick response. Ah too bad, I'm looking to start using it in just a couple weeks.

**Comment by openSourcerer9000** [comment]
So I was able to match up the cell size and everything so that the 2022-present NetCDF's  look like those in the repository.  however, you can clearly see a disconnect between the two datasets. Could I get some more information on  how and why the data was bias corrected? Thanks

![image](https://github.com/danielbwright/RainyDay/assets/61931826/3f06d206-67ae-4144-abfd-5fa07d047944)

**Comment by danielbwright** [comment]
Oh dear. What is the y axis? Probably I should process myself and confirm your result to be sure that everything behaved right-but I'm pretty busy at the moment. If it is indeed an issue with Stage IV itself, there won't be much explanation for it, but there are sometimes useful tidbits here: 
https://data.eol.ucar.edu/dataset/21.093
I don't see anything that would explain this though.

**Comment by openSourcerer9000** [comment]
From the docs:
"Then a bias adjustment is applied in certain conditions such that daily precipitation values are rescaled according to the nClimGrid-Daily dataset (see below). This bias adjustment is included to compensate for biases in ERA5, as well as underestimation by Stage IV in mountainous areas and during cold weather."
It looks like daily totals were disaggregated  from this  dataset? The difference seems extreme though. This  plot is looking at only the gulf of Mexico FYI.

**Comment by openSourcerer9000** [comment]
https://github.com/danielbwright/RainyDay/blob/master/UserGuide/RainyDay_Tutorial.ipynb

**Comment by danielbwright** [comment]
Oh I see. I didn’t realize which data you were pulling. We have a few variants of Stage IV floating around, for better or worse. That one much harder to update, because it requires quite a bit of ancillary data, using some methods I’ve cooked up. I’m also not 100% sure whether I trust it, because I haven’t fully vetted all the bias correction techniques I’ve used. Sorry things are discombobulated-as I said, we’re refactoring everything and the datasets are part of that effort too.

--
Dr. Daniel B. Wright (he/him/his)
Arno Lenz Memorial Associate Professor of Water Resources Engineering
Vilas Faculty Early Career Investigator
Hydroclimate Extremes Research Group (https://her.cee.wisc.edu/)
Civil and Environmental Engineering
University of Wisconsin-Madison



From: Sean Micek ***@***.***>
Date: Monday, March 4, 2024 at 11:48 AM
To: danielbwright/RainyDay ***@***.***>
Cc: Daniel Wright ***@***.***>, Comment ***@***.***>
Subject: Re: [danielbwright/RainyDay] Can we get the script used to reproject STAGE IV data? Or get the recent years of STAGE IV postprocessed? (Issue #2)

https://github.com/danielbwright/RainyDay/blob/master/UserGuide/RainyDay_Tutorial.ipynb<https://urldefense.com/v3/__https:/github.com/danielbwright/RainyDay/blob/master/UserGuide/RainyDay_Tutorial.ipynb__;!!Mak6IKo!Jj5ubDUa6mYB6uaFVB-rCw0owJE9RvF2C42KcH4wDnvFTVAxy0g7LiODnwryiAOI4FRxVKBaBD6lERBDLEdtPsjXRQ0kug$>
